# Generated by Django 4.2.11 on 2024-03-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, upload_to='./static/img'),
        ),
    ]
