# Generated by Django 4.2.5 on 2024-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_books_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sound', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, upload_to='myapp/static/img'),
        ),
    ]
